### ISSUE TITLE
ESP 8266

### ISSUE THREAD

**Issue by proietti1965** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#1]
Any chance you could make your library compatable with ESP8266 as well

**Comment by MkLHX** [comment]
Hello, you can test run it on ESP8266 and give us feeback. If your test run well we add ESP8266 in tested boards.

**Comment by proietti1965** [comment]
Hi,

I have tried it does not compile. Below error: 

//

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp: In member function 'void DFRobot_ESP_PH::begin()':

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:48:36: error: 'class EEPROMClass' has no member named 'readFloat'

 

     this->_neutralVoltage = EEPROM.readFloat(PHVALUEADDR); //load the neutral (pH = 7.0)voltage of the pH board from the EEPROM

 

                                    ^

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:52:16: error: 'class EEPROMClass' has no member named 'writeFloat'

 

         EEPROM.writeFloat(PHVALUEADDR, this->_neutralVoltage);

 

                ^

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:56:33: error: 'class EEPROMClass' has no member named 'readFloat'

 

     this->_acidVoltage = EEPROM.readFloat(PHVALUEADDR + sizeof(float)); //load the acid (pH = 4.0) voltage of the pH board from the EEPROM

 

                                 ^

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:60:16: error: 'class EEPROMClass' has no member named 'writeFloat'

 

         EEPROM.writeFloat(PHVALUEADDR + sizeof(float), this->_acidVoltage);

 

                ^

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp: In member function 'void DFRobot_ESP_PH::phCalibration(byte)':

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:225:28: error: 'class EEPROMClass' has no member named 'writeFloat'

 

                     EEPROM.writeFloat(PHVALUEADDR, this->_neutralVoltage);

 

                            ^

 

C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\DFRobot_ESP_PH_BY_GREENPONIK\DFRobot_ESP_PH.cpp:230:28: error: 'class EEPROMClass' has no member named 'writeFloat'

 

                     EEPROM.writeFloat(PHVALUEADDR + sizeof(float), this->_acidVoltage);

 

                            ^

 

Multiple libraries were found for "EEPROM.h"

Used: C:\Users\proie\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\EEPROM

Not used: C:\Users\proie\Dropbox\ARDUINO\arduino 1.8.9\libraries\EEPROM

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

//

**Comment by MkLHX** [comment]
ok i see whats happen, 

As you can see here https://github.com/esp8266/Arduino/blob/master/libraries/EEPROM/EEPROM.cpp

ESP8266 EEPROM library not have writeFloat and readFloat method.

So if you can write code, you can fork this repository and update code for compatibility with ESP8266.

Today we not use ESP8266 for this kind of applications so we don't need to wrote and maintain spécific code for this kind of chips.
