### ISSUE TITLE
ph value deviation

### ISSUE THREAD

**Issue by r3pek** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#11]
Hi, totally just "pinging" to make sure I'm not doing anything wrong.

I was trying to get a DFRobot Pro PH v2 to work with this but somehow, while it does work, the values reported after calibration (I tried 7 first and than 4 and vice-versa) are always kinda low, even with the same solutions used for calibration. For example, right now i'm reading ~3.80 for the 4.0 solution and 6.80 for the 7.00 solution.
Did I do something wrong or should I use the ADC version? 
Would it help to do a 3 point calibration (I do have a 9ph solution)?

**Comment by MkLHX** [comment]
Hi @r3pek,

Did you try to work with the same reference?

```using Gravity: Analog pH Sensor / Meter Kit V2, SKU:SEN0161-V2```

are you sure you pH probe is clean and not used?

To calibrate with 3 points, this isn't the good way using DFRobot kit.

If you can use electronic with ADC you'll give better resolution to convert voltage into analogue.
