### ISSUE TITLE
can't enter calibration mode by typing enterph

### ISSUE THREAD

**Issue by Jw-Wong** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#12]
As title mentions, can't enter calibration mode when typed enterph. calph also does not work. When the following is entered, nothing changes and the sensor returns the current pH value only.
![image](https://github.com/GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK/assets/94821604/9d9bab55-a432-4d04-8e01-d4824bd1a744)

After entering the command
![image](https://github.com/GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK/assets/94821604/a0fa7d2e-825a-49b2-ac30-4a1af42687a3)

**Comment by MkLHX** [comment]
Hi @Jw-Wong as you can see here https://github.com/GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK/blob/master/src/DFRobot_ESP_PH.cpp#L127

the command is ENTERPH not enterpH

**Comment by Jw-Wong** [comment]
Thank you for such a quick reply! But I'm trying both and the output is still the same
![image](https://github.com/GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK/assets/94821604/cd746c4f-6246-49d8-b065-8eff6cf299d0)

**Comment by MkLHX** [comment]
I'm sorry i don't know what to say.

If you are correctly connected to the serial and send the good command, the lib will work.

We stopped to use it since 4 years so maybe something is wrong now with the same lib.

Maybe the interval of your loop is too low try to increase it give the time to the serial to catch the command from monitor input

**Comment by Jw-Wong** [comment]
Okay, I'll try the following you mentioned. Previously I was using the arduino code for the conductivity sensor on my esp 32 so the readings were off. But I was still able to enter the electrical conductivity calibration mode. however when I tried the arduino code for ph it wouldn't let me enter calibration mode as well (readings were still NaN regardless). I will continue tinkering to see if i can find a fix. Would you recommend using a ADC for the pH sensor as well?

**Comment by Jw-Wong** [comment]
Issue resolved,  arduino terminal was set to "No Line Ending" when it should be set to "New Line"
![image](https://github.com/GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK/assets/94821604/8236c957-0481-4257-9469-00093a69a754)

**Comment by MkLHX** [comment]
Hi @Jw-Wong good to ear
