### ISSUE TITLE
High voltage and ESP32 ADC problem

### ISSUE THREAD

**Issue by garudaonekh** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#4]
Hi,
ESP32 can only accept 3.3 voltage. But as I know, this PH sensor can generate up to 5v.

Another issue is there're many rumor that ESP32 analog read is terrible. DO you have any comment on these issues?

Thanks

**Comment by MkLHX** [comment]
Hi sorry for late answer.

This is not an issue about our library but about electronic.

I just provide support about our library, it's not possible to give any advice about electronic here and with so less elements.

**Comment by guestisp** [comment]
> ESP32 can only accept 3.3 voltage. But as I know, this PH sensor can generate up to 5v.

the v2 has an analog OUTPUT range from 0v to 3v, you can power it up to 5v, but the output coming back to the ESP is 3v max.
