### ISSUE TITLE
analogReadMillivolts

### ISSUE THREAD

**Issue by guestisp** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#8]
Why not using the native ESP `analogReadMilliVolts` and drop the formula to convert from `analogRead`  ?

ESP has a native millivolt reading function.

Also, do  you know how to calibrate with a different solution, in example, ph 7.5 or ph 10 ?

**Comment by MkLHX** [comment]
Hello, because we take the source code from [DFRobot](https://github.com/DFRobot/DFRobot_EC)

To calibrate with different  buffer solutions you have to build you own version of range of AnalogRead values

**Comment by guestisp** [comment]
but do you think issue could rise using the analogreadmillivolts? seems stable here but values are different (100-200mv) than the analogread plus convertion. don't know which one to trust

do you have a sample or a pseudocode to use for calibrating with different pH values?

(which accuracy are you getting? something in the range of 0.1 or 0.01?)

**Comment by MkLHX** [comment]
Hello, i haven't any sample or something to help user to create they own version.
Because we not use DFRobot technology anymore to read ph or ec in water.

**Comment by guestisp** [comment]
do you use better hardware? which one?
